version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: thepub-pelican-panel_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/pelican-dev/panel:latest
    restart: on-failure
    ports:
      - 4040:80/tcp
      - 4040:80/udp
      - 4041:443/tcp
      - 4041:443/udp
    volumes:
      - ${APP_DATA_DIR}/data/pelican/data:/pelican-data
      - ${APP_DATA_DIR}/data/pelican/logs:/var/www/html/storage/logs